# Google Cloud Platform's microservices-demo (Online Boutique)
# A cloud-first microservices demo application consisting of 11 services
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microservices-demo
  namespace: dorkomen
spec:
  targetNamespace: microservices-demo
  releaseName: microservices-demo
  interval: 10m
  chart:
    spec:
      chart: helm-chart
      sourceRef:
        kind: GitRepository
        name: microservices-demo
        namespace: dorkomen
      interval: 5m
  install:
    remediation:
      retries: -1
    createNamespace: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: ConfigMap
      name: microservices-demo-values
      optional: true
  values:
    # Frontend service configuration
    # Disable external LoadBalancer service to avoid timeout issues in local environments
    frontend:
      externalService: false
      cymbalBranding: false

    # Service accounts
    serviceAccounts:
      create: true

    # Network policies (disabled by default)
    networkPolicies:
      create: false

    # Default resource configurations
    cartService:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 128Mi

    checkoutService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    currencyService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    emailService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    paymentService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    productCatalogService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    recommendationService:
      resources:
        requests:
          cpu: 100m
          memory: 220Mi
        limits:
          cpu: 200m
          memory: 450Mi

    shippingService:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    adService:
      resources:
        requests:
          cpu: 200m
          memory: 180Mi
        limits:
          cpu: 300m
          memory: 300Mi
