# Shared namespace for Online Boutique microservices
apiVersion: v1
kind: Namespace
metadata:
  name: online-boutique
  labels:
    app.kubernetes.io/name: online-boutique
    app.kubernetes.io/part-of: online-boutique
    istio-injection: disabled
